FROM python:{{ python_version }}

# avoid .pyc files, unbuffered output
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# install system build tools
RUN apt-get update \
    && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*

    
# install uv itself
RUN pip install --upgrade pip uv

# Set working directory inside container
WORKDIR /app

# sync all deps and export a requirements.txt
RUN uv export --no-hashes --format requirements-txt > requirements.txt

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files into the container
COPY . .

# Expose port for FastAPI (default 8000)
EXPOSE {{ expose_port }}

# Command to run the app using uvicorn
CMD ["uvicorn", "{{ app_module }}:app", "--host", "0.0.0.0", "--port", "{{ expose_port }}"]
 